### ISSUE TITLE
后端出错了

### ISSUE THREAD

**Issue by emeomo** [rocboss/rocboss-api#3]
https://api.rongbuqiu.com

Warning: require(/www/wwwroot/rocboss-api/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/rocboss-api/bootstrap/init.php on line 11

Fatal error: require(): Failed opening required '/www/wwwroot/rocboss-api/bootstrap/../vendor/autoload.php' (include_path='.:/www/server/php/70/lib/php') in /www/wwwroot/rocboss-api/bootstrap/init.php on line 11

**Comment by emeomo** [comment]
1. 使用环境（PHP7.0 开发环境）
2. web访问根目录指向 public 目录
![](https://puui.qpic.cn/fans_admin/0/3_620862694_1580388194719/0)

**Comment by rocboss** [comment]
需要先安装依赖
```
composer install
```

**Comment by emeomo** [comment]
Fatal error: Uncaught Elastica\Exception\ResponseException: unknown key [number_of_replicas] for create index in /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:181 Stack trace: #0 /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Request.php(193): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #1 /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Client.php(688): Elastica\Request->send() #2 /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Client.php(720): Elastica\Client->request('rocboss-logs-20...', 'PUT', Array, Array) #3 /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Index.php(585): Elastica\Client->requestEndpoint(Object(Elasticsearch\Endpoints\Indices\Create)) #4 /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Index.php(319): Elastica\Index->requestEndpoint(Object(Elasticsearch\Endpoints\Indices\Create)) #5 /www/wwwroot/rocboss-api/app/core/Batio.php(144): Elastica\Index->create(Array) #6 [internal function]: in /www/wwwroot/rocboss-api/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 181

**Comment by rocboss** [comment]
1. 确保ElasticSearch服务已开启
2. 确认下ElasticSearch版本
```
# curl http://yourip:9200
```

推测你使用了es7.x版本，有些API废弃了。
如果是Docker安装，使用如下命令重新安装

```
# rm -rf /var/elasticsearch
# mkdir -p /var/elasticsearch/data
# mkdir -p /var/elasticsearch/logs
# docker run -it  -e ES_JAVA_OPTS="-Xms1024m -Xmx1024m" --name elasticsearch -d -p 9200:9200 -p 9300:9300 -p 5601:5601 -v /var/elasticsearch/data:/usr/share/elasticsearch/data -v /var/elasticsearch/logs:/usr/share/elasticsearch/logs fahchen/elasticsearch-analysis-ik:6.4.2
```

**Comment by emeomo** [comment]
我放弃了ElasticSearch搞不好  我太菜了。。。

**Comment by rocboss** [comment]
别放弃，出现啥问题可以多尝试搜索。Docker安装不了吗？这些步骤我都测试过，应该都可以正常运行的

**Comment by emeomo** [comment]
Docker是在宝塔安装的  启动不了ElasticSearch

![我还单独开了个服务器搭建ElasticSearch半天也没弄好  心态爆炸](https://puui.qpic.cn/fans_admin/0/3_547607168_1580466826474/0)

**Comment by rocboss** [comment]
ROCBOSS官网私信我一下，加个QQ，我帮你看下

**Comment by rocboss** [comment]
Finished

**Comment by Ya-hui** [comment]
该问题解决了吗？ 我也碰到了这个问题
