### ISSUE TITLE
unknown key [number_of_replicas] for create index

### ISSUE THREAD

**Issue by Ya-hui** [rocboss/rocboss-api#5]
单机服务

![image](https://user-images.githubusercontent.com/13138164/79039662-6e01f180-7c15-11ea-85e9-3f06dc5a5f75.png)
elasticsearch 已经安装 curl localhost:9200 也能访问到

.env文件
![image](https://user-images.githubusercontent.com/13138164/79039686-9a1d7280-7c15-11ea-97ba-cb6f83146971.png)
代码运行 报错

![image](https://user-images.githubusercontent.com/13138164/79039693-a9042500-7c15-11ea-93d7-1b8e42ce068a.png)

已经试过把包elasticsearch/elasticsearch升到7.4还是不行

**Comment by rocboss** [comment]
用官方文档里的 6.4.2 版本

**Comment by Ya-hui** [comment]
![image](https://user-images.githubusercontent.com/13138164/79040421-f6cf5c00-7c1a-11ea-827c-86e89e64b049.png)
现在是刚下载下来的版本 ， 需要 把elasticsearch/elasticsearch改成6.4版本？

**Comment by rocboss** [comment]
是你ES的版本，不是依赖包的版本

**Comment by Ya-hui** [comment]
好的，我试下

**Comment by Ya-hui** [comment]
问题已成功解决
